/* eslint-disable camelcase */
import { Nunito_Sans } from "next/font/google";

import { UserContextProvider } from "@/providers/contexts/UserContextProvider";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import { SideMenuProvider } from "@/providers/SideMenuProvider";
import { SWRProvider } from "@/providers/SWRProvider";
import "./globals.css";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Book Wise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="text-gray-100 bg-gray-800" lang="en">
      <body className={nunito.className}>
        <NextAuthProvider>
          <UserContextProvider>
            <SWRProvider>
              <SideMenuProvider>{children}</SideMenuProvider>
            </SWRProvider>
          </UserContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
